title: Anna Bison 🇮🇹
description: MSc student at UniPD
theme: jekyll-theme-minimal
social_links:
  - name: linkedin
    url: https://www.linkedin.com/in/annabison
  - name: email
    url: mailto:anna.bison@pm.me
  - name: instagram
    url: https://instagram.com/annabison_
  
